# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audio.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'audio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61udio.proto\x12\x05\x61udio\"\"\n\x0c\x41udioRequest\x12\x12\n\naudio_path\x18\x01 \x01(\t\"r\n\rAudioResponse\x12\x0f\n\x07pitches\x18\x01 \x03(\x02\x12\r\n\x05times\x18\x02 \x03(\x02\x12\x12\n\nchromagram\x18\x03 \x01(\x0c\x12\r\n\x05tempo\x18\x04 \x01(\x02\x12\n\n\x02sr\x18\x05 \x01(\x02\x12\x12\n\nhop_length\x18\x06 \x01(\x05\x32J\n\rAudioAnalyzer\x12\x39\n\x0cProcessAudio\x12\x13.audio.AudioRequest\x1a\x14.audio.AudioResponseB\x15Z\x13internal/audioprotob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\023internal/audioproto'
  _globals['_AUDIOREQUEST']._serialized_start=22
  _globals['_AUDIOREQUEST']._serialized_end=56
  _globals['_AUDIORESPONSE']._serialized_start=58
  _globals['_AUDIORESPONSE']._serialized_end=172
  _globals['_AUDIOANALYZER']._serialized_start=174
  _globals['_AUDIOANALYZER']._serialized_end=248
# @@protoc_insertion_point(module_scope)
