# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: separator.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'separator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fseparator.proto\x12\tseparator\"?\n\x0fSeparateRequest\x12,\n\naudio_data\x18\x01 \x01(\x0b\x32\x18.separator.AudioFileData\"\x91\x01\n\x10SeparateResponse\x12\x35\n\x05stems\x18\x01 \x03(\x0b\x32&.separator.SeparateResponse.StemsEntry\x1a\x46\n\nStemsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.separator.AudioFileData:\x02\x38\x01\"7\n\rAudioFileData\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x13\n\x0b\x61udio_bytes\x18\x02 \x01(\x0c\x32Z\n\x0e\x41udioSeparator\x12H\n\rSeparateAudio\x12\x1a.separator.SeparateRequest\x1a\x1b.separator.SeparateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'separator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEPARATERESPONSE_STEMSENTRY']._loaded_options = None
  _globals['_SEPARATERESPONSE_STEMSENTRY']._serialized_options = b'8\001'
  _globals['_SEPARATEREQUEST']._serialized_start=30
  _globals['_SEPARATEREQUEST']._serialized_end=93
  _globals['_SEPARATERESPONSE']._serialized_start=96
  _globals['_SEPARATERESPONSE']._serialized_end=241
  _globals['_SEPARATERESPONSE_STEMSENTRY']._serialized_start=171
  _globals['_SEPARATERESPONSE_STEMSENTRY']._serialized_end=241
  _globals['_AUDIOFILEDATA']._serialized_start=243
  _globals['_AUDIOFILEDATA']._serialized_end=298
  _globals['_AUDIOSEPARATOR']._serialized_start=300
  _globals['_AUDIOSEPARATOR']._serialized_end=390
# @@protoc_insertion_point(module_scope)
