# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: note_analyzer.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'note_analyzer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13note_analyzer.proto\x12\x0bnoteanlyzer\">\n\x0c\x41udioRequest\x12.\n\naudio_data\x18\x01 \x01(\x0b\x32\x1a.noteanlyzer.AudioFileData\"5\n\x0cNoteResponse\x12%\n\x05notes\x18\x01 \x03(\x0b\x32\x16.noteanlyzer.NoteEvent\"7\n\rAudioFileData\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x13\n\x0b\x61udio_bytes\x18\x02 \x01(\x0c\"b\n\tNoteEvent\x12\x15\n\rstart_seconds\x18\x01 \x01(\x02\x12\x12\n\nmidi_pitch\x18\x02 \x01(\x05\x12\x10\n\x08velocity\x18\x03 \x01(\x02\x12\x18\n\x10\x64uration_seconds\x18\x04 \x01(\x02\x32O\n\x0cNoteAnalyzer\x12?\n\x07\x41nalyze\x12\x19.noteanlyzer.AudioRequest\x1a\x19.noteanlyzer.NoteResponseB\x1eZ\x1cinternal/proto/note-analyzerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'note_analyzer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\034internal/proto/note-analyzer'
  _globals['_AUDIOREQUEST']._serialized_start=36
  _globals['_AUDIOREQUEST']._serialized_end=98
  _globals['_NOTERESPONSE']._serialized_start=100
  _globals['_NOTERESPONSE']._serialized_end=153
  _globals['_AUDIOFILEDATA']._serialized_start=155
  _globals['_AUDIOFILEDATA']._serialized_end=210
  _globals['_NOTEEVENT']._serialized_start=212
  _globals['_NOTEEVENT']._serialized_end=310
  _globals['_NOTEANALYZER']._serialized_start=312
  _globals['_NOTEANALYZER']._serialized_end=391
# @@protoc_insertion_point(module_scope)
