services:
  api-gateway:
    build: ./api-gateway
    env_file:
      - /api-gateway/.env
    ports:
      - "8080:8080"
    depends_on:
      - audio-separator
      - tab-generator
  
  audio-separator:
    build: ./audio-separator
    env_file:
      - /audio-separator/.env
    ports:
      - "50054:50054"
    
  tab-generator:
    build: ./tab-generator
    env_file:
      - /tab-generator/.env
    ports:
      - "50052:50052"
    depends_on:
      - analyzer
  
  analyzer:
    build: ./analyzer
    env_file:
      - ./analyzer/.env
    ports:
      - "50051:50051"