services:
  api-gateway:
    build: ./api-gateway
    env_file:
      - /api-gateway/.env
    ports:
      - "8080:8080"
    depends_on:
      - audio-separator
      - audio-processor
      - tab-generator
  
  audio-processor:
    build: ./audio-preprocessor
    env_file:
      - /audio-preprocessor/.env
    ports:
      - "50053:50053"
  
  audio-separator:
    build: ./audio-separator
    env_file:
      - /audio-separator/.env
    ports:
      - "50054:50054"
    
  tab-generator:
    build: ./tab-generator
    env_file:
      - /tab-generator/.env
    ports:
      - "50052:50052"
    depends_on:
      - onsets-frames
  
  onsets-frames:
    build: ./onsets-frames
    env_file:
      - ./onsets-frames/.env
    ports:
      - "50055:50055"