// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=../mocks/service_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	url "net/url"
	reflect "reflect"
	models "tabgen/internal/models"
	time "time"

	types "github.com/aws/aws-sdk-go-v2/service/s3/types"
	gomock "go.uber.org/mock/gomock"
)

// MockTabGenTaskRepository is a mock of TabGenTaskRepository interface.
type MockTabGenTaskRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTabGenTaskRepositoryMockRecorder
	isgomock struct{}
}

// MockTabGenTaskRepositoryMockRecorder is the mock recorder for MockTabGenTaskRepository.
type MockTabGenTaskRepositoryMockRecorder struct {
	mock *MockTabGenTaskRepository
}

// NewMockTabGenTaskRepository creates a new mock instance.
func NewMockTabGenTaskRepository(ctrl *gomock.Controller) *MockTabGenTaskRepository {
	mock := &MockTabGenTaskRepository{ctrl: ctrl}
	mock.recorder = &MockTabGenTaskRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTabGenTaskRepository) EXPECT() *MockTabGenTaskRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTabGenTaskRepository) Create(ctx context.Context, task *models.TabGenTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTabGenTaskRepositoryMockRecorder) Create(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTabGenTaskRepository)(nil).Create), ctx, task)
}

// Get mocks base method.
func (m *MockTabGenTaskRepository) Get(ctx context.Context, id string) (*models.TabGenTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*models.TabGenTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTabGenTaskRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTabGenTaskRepository)(nil).Get), ctx, id)
}

// GetByAudioSepTaskID mocks base method.
func (m *MockTabGenTaskRepository) GetByAudioSepTaskID(ctx context.Context, id string) (*models.TabGenTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAudioSepTaskID", ctx, id)
	ret0, _ := ret[0].(*models.TabGenTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAudioSepTaskID indicates an expected call of GetByAudioSepTaskID.
func (mr *MockTabGenTaskRepositoryMockRecorder) GetByAudioSepTaskID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAudioSepTaskID", reflect.TypeOf((*MockTabGenTaskRepository)(nil).GetByAudioSepTaskID), ctx, id)
}

// MarkSaved mocks base method.
func (m *MockTabGenTaskRepository) MarkSaved(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkSaved", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkSaved indicates an expected call of MarkSaved.
func (mr *MockTabGenTaskRepositoryMockRecorder) MarkSaved(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSaved", reflect.TypeOf((*MockTabGenTaskRepository)(nil).MarkSaved), ctx, id)
}

// TryUpdateStatus mocks base method.
func (m *MockTabGenTaskRepository) TryUpdateStatus(ctx context.Context, id string, fromStatus []models.Status, to models.Status, errMsg, resultTabName *string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryUpdateStatus", ctx, id, fromStatus, to, errMsg, resultTabName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TryUpdateStatus indicates an expected call of TryUpdateStatus.
func (mr *MockTabGenTaskRepositoryMockRecorder) TryUpdateStatus(ctx, id, fromStatus, to, errMsg, resultTabName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryUpdateStatus", reflect.TypeOf((*MockTabGenTaskRepository)(nil).TryUpdateStatus), ctx, id, fromStatus, to, errMsg, resultTabName)
}

// MockAudioSepTaskRepository is a mock of AudioSepTaskRepository interface.
type MockAudioSepTaskRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAudioSepTaskRepositoryMockRecorder
	isgomock struct{}
}

// MockAudioSepTaskRepositoryMockRecorder is the mock recorder for MockAudioSepTaskRepository.
type MockAudioSepTaskRepositoryMockRecorder struct {
	mock *MockAudioSepTaskRepository
}

// NewMockAudioSepTaskRepository creates a new mock instance.
func NewMockAudioSepTaskRepository(ctrl *gomock.Controller) *MockAudioSepTaskRepository {
	mock := &MockAudioSepTaskRepository{ctrl: ctrl}
	mock.recorder = &MockAudioSepTaskRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAudioSepTaskRepository) EXPECT() *MockAudioSepTaskRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAudioSepTaskRepository) Create(ctx context.Context, task *models.AudioSepTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAudioSepTaskRepositoryMockRecorder) Create(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAudioSepTaskRepository)(nil).Create), ctx, task)
}

// Get mocks base method.
func (m *MockAudioSepTaskRepository) Get(ctx context.Context, id string) (*models.AudioSepTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*models.AudioSepTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAudioSepTaskRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAudioSepTaskRepository)(nil).Get), ctx, id)
}

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
	isgomock struct{}
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// GetFile mocks base method.
func (m *MockStorage) GetFile(ctx context.Context, bucketName, objectName string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFile", ctx, bucketName, objectName)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFile indicates an expected call of GetFile.
func (mr *MockStorageMockRecorder) GetFile(ctx, bucketName, objectName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFile", reflect.TypeOf((*MockStorage)(nil).GetFile), ctx, bucketName, objectName)
}

// ListFilesByPrefix mocks base method.
func (m *MockStorage) ListFilesByPrefix(ctx context.Context, bucketName, prefix string) ([]types.Object, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFilesByPrefix", ctx, bucketName, prefix)
	ret0, _ := ret[0].([]types.Object)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFilesByPrefix indicates an expected call of ListFilesByPrefix.
func (mr *MockStorageMockRecorder) ListFilesByPrefix(ctx, bucketName, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFilesByPrefix", reflect.TypeOf((*MockStorage)(nil).ListFilesByPrefix), ctx, bucketName, prefix)
}

// PresignedGet mocks base method.
func (m *MockStorage) PresignedGet(ctx context.Context, bucket, object string, exp time.Duration) (*url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresignedGet", ctx, bucket, object, exp)
	ret0, _ := ret[0].(*url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignedGet indicates an expected call of PresignedGet.
func (mr *MockStorageMockRecorder) PresignedGet(ctx, bucket, object, exp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignedGet", reflect.TypeOf((*MockStorage)(nil).PresignedGet), ctx, bucket, object, exp)
}

// RemoveFile mocks base method.
func (m *MockStorage) RemoveFile(ctx context.Context, bucketName, objectName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFile", ctx, bucketName, objectName)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFile indicates an expected call of RemoveFile.
func (mr *MockStorageMockRecorder) RemoveFile(ctx, bucketName, objectName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFile", reflect.TypeOf((*MockStorage)(nil).RemoveFile), ctx, bucketName, objectName)
}

// UploadFile mocks base method.
func (m *MockStorage) UploadFile(ctx context.Context, bucketName, objectName string, reader io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", ctx, bucketName, objectName, reader)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockStorageMockRecorder) UploadFile(ctx, bucketName, objectName, reader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockStorage)(nil).UploadFile), ctx, bucketName, objectName, reader)
}

// MockTxManager is a mock of TxManager interface.
type MockTxManager struct {
	ctrl     *gomock.Controller
	recorder *MockTxManagerMockRecorder
	isgomock struct{}
}

// MockTxManagerMockRecorder is the mock recorder for MockTxManager.
type MockTxManagerMockRecorder struct {
	mock *MockTxManager
}

// NewMockTxManager creates a new mock instance.
func NewMockTxManager(ctrl *gomock.Controller) *MockTxManager {
	mock := &MockTxManager{ctrl: ctrl}
	mock.recorder = &MockTxManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxManager) EXPECT() *MockTxManagerMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockTxManager) Do(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Do indicates an expected call of Do.
func (mr *MockTxManagerMockRecorder) Do(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockTxManager)(nil).Do), ctx, fn)
}
