// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: tab.proto

package tab

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TabRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        []*AudioChunk          `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TabRequest) Reset() {
	*x = TabRequest{}
	mi := &file_tab_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TabRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TabRequest) ProtoMessage() {}

func (x *TabRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tab_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TabRequest.ProtoReflect.Descriptor instead.
func (*TabRequest) Descriptor() ([]byte, []int) {
	return file_tab_proto_rawDescGZIP(), []int{0}
}

func (x *TabRequest) GetChunks() []*AudioChunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type AudioChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     float32                `protobuf:"fixed32,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	AudioData     []byte                 `protobuf:"bytes,2,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_tab_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_tab_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_tab_proto_rawDescGZIP(), []int{1}
}

func (x *AudioChunk) GetStartTime() float32 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *AudioChunk) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

type TabResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tab           string                 `protobuf:"bytes,1,opt,name=tab,proto3" json:"tab,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TabResponse) Reset() {
	*x = TabResponse{}
	mi := &file_tab_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TabResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TabResponse) ProtoMessage() {}

func (x *TabResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tab_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TabResponse.ProtoReflect.Descriptor instead.
func (*TabResponse) Descriptor() ([]byte, []int) {
	return file_tab_proto_rawDescGZIP(), []int{2}
}

func (x *TabResponse) GetTab() string {
	if x != nil {
		return x.Tab
	}
	return ""
}

var File_tab_proto protoreflect.FileDescriptor

const file_tab_proto_rawDesc = "" +
	"\n" +
	"\ttab.proto\x12\x03tab\"5\n" +
	"\n" +
	"TabRequest\x12'\n" +
	"\x06chunks\x18\x01 \x03(\v2\x0f.tab.AudioChunkR\x06chunks\"J\n" +
	"\n" +
	"AudioChunk\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\x02R\tstartTime\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x02 \x01(\fR\taudioData\"\x1f\n" +
	"\vTabResponse\x12\x10\n" +
	"\x03tab\x18\x01 \x01(\tR\x03tab2?\n" +
	"\vTabGenerate\x120\n" +
	"\vGenerateTab\x12\x0f.tab.TabRequest\x1a\x10.tab.TabResponseB\x14Z\x12internal/proto/tabb\x06proto3"

var (
	file_tab_proto_rawDescOnce sync.Once
	file_tab_proto_rawDescData []byte
)

func file_tab_proto_rawDescGZIP() []byte {
	file_tab_proto_rawDescOnce.Do(func() {
		file_tab_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tab_proto_rawDesc), len(file_tab_proto_rawDesc)))
	})
	return file_tab_proto_rawDescData
}

var file_tab_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tab_proto_goTypes = []any{
	(*TabRequest)(nil),  // 0: tab.TabRequest
	(*AudioChunk)(nil),  // 1: tab.AudioChunk
	(*TabResponse)(nil), // 2: tab.TabResponse
}
var file_tab_proto_depIdxs = []int32{
	1, // 0: tab.TabRequest.chunks:type_name -> tab.AudioChunk
	0, // 1: tab.TabGenerate.GenerateTab:input_type -> tab.TabRequest
	2, // 2: tab.TabGenerate.GenerateTab:output_type -> tab.TabResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tab_proto_init() }
func file_tab_proto_init() {
	if File_tab_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tab_proto_rawDesc), len(file_tab_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tab_proto_goTypes,
		DependencyIndexes: file_tab_proto_depIdxs,
		MessageInfos:      file_tab_proto_msgTypes,
	}.Build()
	File_tab_proto = out.File
	file_tab_proto_goTypes = nil
	file_tab_proto_depIdxs = nil
}
