// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: separator.proto

package separator

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AudioSeparator_SeparateAudio_FullMethodName = "/separator.AudioSeparator/SeparateAudio"
)

// AudioSeparatorClient is the client API for AudioSeparator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AudioSeparatorClient interface {
	SeparateAudio(ctx context.Context, in *SeparateRequest, opts ...grpc.CallOption) (*SeparateResponse, error)
}

type audioSeparatorClient struct {
	cc grpc.ClientConnInterface
}

func NewAudioSeparatorClient(cc grpc.ClientConnInterface) AudioSeparatorClient {
	return &audioSeparatorClient{cc}
}

func (c *audioSeparatorClient) SeparateAudio(ctx context.Context, in *SeparateRequest, opts ...grpc.CallOption) (*SeparateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SeparateResponse)
	err := c.cc.Invoke(ctx, AudioSeparator_SeparateAudio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AudioSeparatorServer is the server API for AudioSeparator service.
// All implementations must embed UnimplementedAudioSeparatorServer
// for forward compatibility.
type AudioSeparatorServer interface {
	SeparateAudio(context.Context, *SeparateRequest) (*SeparateResponse, error)
	mustEmbedUnimplementedAudioSeparatorServer()
}

// UnimplementedAudioSeparatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAudioSeparatorServer struct{}

func (UnimplementedAudioSeparatorServer) SeparateAudio(context.Context, *SeparateRequest) (*SeparateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SeparateAudio not implemented")
}
func (UnimplementedAudioSeparatorServer) mustEmbedUnimplementedAudioSeparatorServer() {}
func (UnimplementedAudioSeparatorServer) testEmbeddedByValue()                        {}

// UnsafeAudioSeparatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AudioSeparatorServer will
// result in compilation errors.
type UnsafeAudioSeparatorServer interface {
	mustEmbedUnimplementedAudioSeparatorServer()
}

func RegisterAudioSeparatorServer(s grpc.ServiceRegistrar, srv AudioSeparatorServer) {
	// If the following call pancis, it indicates UnimplementedAudioSeparatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AudioSeparator_ServiceDesc, srv)
}

func _AudioSeparator_SeparateAudio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeparateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioSeparatorServer).SeparateAudio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AudioSeparator_SeparateAudio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioSeparatorServer).SeparateAudio(ctx, req.(*SeparateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AudioSeparator_ServiceDesc is the grpc.ServiceDesc for AudioSeparator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AudioSeparator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "separator.AudioSeparator",
	HandlerType: (*AudioSeparatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SeparateAudio",
			Handler:    _AudioSeparator_SeparateAudio_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "separator.proto",
}
