// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proto/fx_processor.proto
#ifndef GRPC_proto_2ffx_5fprocessor_2eproto__INCLUDED
#define GRPC_proto_2ffx_5fprocessor_2eproto__INCLUDED

#include "proto/fx_processor.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace fxp {

class FXProcessor final {
 public:
  static constexpr char const* service_full_name() {
    return "fxp.FXProcessor";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status ProcessAudio(::grpc::ClientContext* context, const ::fxp::AudioRequest& request, ::fxp::AudioRequest* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fxp::AudioRequest>> AsyncProcessAudio(::grpc::ClientContext* context, const ::fxp::AudioRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fxp::AudioRequest>>(AsyncProcessAudioRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::fxp::AudioRequest>* AsyncProcessAudioRaw(::grpc::ClientContext* context, const ::fxp::AudioRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status ProcessAudio(::grpc::ClientContext* context, const ::fxp::AudioRequest& request, ::fxp::AudioRequest* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fxp::AudioRequest>> AsyncProcessAudio(::grpc::ClientContext* context, const ::fxp::AudioRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fxp::AudioRequest>>(AsyncProcessAudioRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::fxp::AudioRequest>* AsyncProcessAudioRaw(::grpc::ClientContext* context, const ::fxp::AudioRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::RpcMethod rpcmethod_ProcessAudio_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ProcessAudio(::grpc::ServerContext* context, const ::fxp::AudioRequest* request, ::fxp::AudioRequest* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ProcessAudio : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_ProcessAudio() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ProcessAudio() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessAudio(::grpc::ServerContext* context, const ::fxp::AudioRequest* request, ::fxp::AudioRequest* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestProcessAudio(::grpc::ServerContext* context, ::fxp::AudioRequest* request, ::grpc::ServerAsyncResponseWriter< ::fxp::AudioRequest>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ProcessAudio<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_ProcessAudio : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_ProcessAudio() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ProcessAudio() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessAudio(::grpc::ServerContext* context, const ::fxp::AudioRequest* request, ::fxp::AudioRequest* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ProcessAudio : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_ProcessAudio() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::StreamedUnaryHandler< ::fxp::AudioRequest, ::fxp::AudioRequest>(std::bind(&WithStreamedUnaryMethod_ProcessAudio<BaseClass>::StreamedProcessAudio, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_ProcessAudio() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ProcessAudio(::grpc::ServerContext* context, const ::fxp::AudioRequest* request, ::fxp::AudioRequest* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedProcessAudio(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::fxp::AudioRequest,::fxp::AudioRequest>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ProcessAudio<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ProcessAudio<Service > StreamedService;
};

}  // namespace fxp


#endif  // GRPC_proto_2ffx_5fprocessor_2eproto__INCLUDED
