// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/audio_processor.proto
// Protobuf C++ Version: 5.27.0

#include "audio_processor.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace audioproc {

inline constexpr ProcessAudioResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : wav_data_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ProcessAudioResponse::ProcessAudioResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ProcessAudioResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProcessAudioResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProcessAudioResponseDefaultTypeInternal() {}
  union {
    ProcessAudioResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProcessAudioResponseDefaultTypeInternal _ProcessAudioResponse_default_instance_;

inline constexpr AudioProcessingConfig::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : threshold_{0},
        margin_{0},
        high_pass_{0},
        use_bandpass_{false},
        band_low_{0},
        band_high_{0},
        fade_samples_{0},
        sample_rate_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR AudioProcessingConfig::AudioProcessingConfig(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct AudioProcessingConfigDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AudioProcessingConfigDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AudioProcessingConfigDefaultTypeInternal() {}
  union {
    AudioProcessingConfig _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AudioProcessingConfigDefaultTypeInternal _AudioProcessingConfig_default_instance_;

inline constexpr ProcessAudioRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        wav_data_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        file_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        config_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR ProcessAudioRequest::ProcessAudioRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ProcessAudioRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProcessAudioRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProcessAudioRequestDefaultTypeInternal() {}
  union {
    ProcessAudioRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProcessAudioRequestDefaultTypeInternal _ProcessAudioRequest_default_instance_;
}  // namespace audioproc
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_proto_2faudio_5fprocessor_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_proto_2faudio_5fprocessor_2eproto = nullptr;
const ::uint32_t
    TableStruct_proto_2faudio_5fprocessor_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::audioproc::AudioProcessingConfig, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::audioproc::AudioProcessingConfig, _impl_.threshold_),
        PROTOBUF_FIELD_OFFSET(::audioproc::AudioProcessingConfig, _impl_.margin_),
        PROTOBUF_FIELD_OFFSET(::audioproc::AudioProcessingConfig, _impl_.high_pass_),
        PROTOBUF_FIELD_OFFSET(::audioproc::AudioProcessingConfig, _impl_.use_bandpass_),
        PROTOBUF_FIELD_OFFSET(::audioproc::AudioProcessingConfig, _impl_.band_low_),
        PROTOBUF_FIELD_OFFSET(::audioproc::AudioProcessingConfig, _impl_.band_high_),
        PROTOBUF_FIELD_OFFSET(::audioproc::AudioProcessingConfig, _impl_.fade_samples_),
        PROTOBUF_FIELD_OFFSET(::audioproc::AudioProcessingConfig, _impl_.sample_rate_),
        PROTOBUF_FIELD_OFFSET(::audioproc::ProcessAudioRequest, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::audioproc::ProcessAudioRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::audioproc::ProcessAudioRequest, _impl_.wav_data_),
        PROTOBUF_FIELD_OFFSET(::audioproc::ProcessAudioRequest, _impl_.file_name_),
        PROTOBUF_FIELD_OFFSET(::audioproc::ProcessAudioRequest, _impl_.config_),
        ~0u,
        ~0u,
        0,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::audioproc::ProcessAudioResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::audioproc::ProcessAudioResponse, _impl_.wav_data_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::audioproc::AudioProcessingConfig)},
        {16, 27, -1, sizeof(::audioproc::ProcessAudioRequest)},
        {30, -1, -1, sizeof(::audioproc::ProcessAudioResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::audioproc::_AudioProcessingConfig_default_instance_._instance,
    &::audioproc::_ProcessAudioRequest_default_instance_._instance,
    &::audioproc::_ProcessAudioResponse_default_instance_._instance,
};
const char descriptor_table_protodef_proto_2faudio_5fprocessor_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\033proto/audio_processor.proto\022\taudioproc"
    "\"\263\001\n\025AudioProcessingConfig\022\021\n\tthreshold\030"
    "\001 \001(\002\022\016\n\006margin\030\002 \001(\005\022\021\n\thigh_pass\030\003 \001(\002"
    "\022\024\n\014use_bandpass\030\004 \001(\010\022\020\n\010band_low\030\005 \001(\002"
    "\022\021\n\tband_high\030\006 \001(\002\022\024\n\014fade_samples\030\007 \001("
    "\005\022\023\n\013sample_rate\030\010 \001(\005\"l\n\023ProcessAudioRe"
    "quest\022\020\n\010wav_data\030\001 \001(\014\022\021\n\tfile_name\030\002 \001"
    "(\t\0220\n\006config\030\003 \001(\0132 .audioproc.AudioProc"
    "essingConfig\"(\n\024ProcessAudioResponse\022\020\n\010"
    "wav_data\030\001 \001(\0142h\n\025AudioProcessorService\022"
    "O\n\014ProcessAudio\022\036.audioproc.ProcessAudio"
    "Request\032\037.audioproc.ProcessAudioResponse"
    "B\031Z\027internal/audioprocprotob\006proto3"
};
static ::absl::once_flag descriptor_table_proto_2faudio_5fprocessor_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_proto_2faudio_5fprocessor_2eproto = {
    false,
    false,
    515,
    descriptor_table_protodef_proto_2faudio_5fprocessor_2eproto,
    "proto/audio_processor.proto",
    &descriptor_table_proto_2faudio_5fprocessor_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_proto_2faudio_5fprocessor_2eproto::offsets,
    file_level_enum_descriptors_proto_2faudio_5fprocessor_2eproto,
    file_level_service_descriptors_proto_2faudio_5fprocessor_2eproto,
};
namespace audioproc {
// ===================================================================

class AudioProcessingConfig::_Internal {
 public:
};

AudioProcessingConfig::AudioProcessingConfig(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:audioproc.AudioProcessingConfig)
}
AudioProcessingConfig::AudioProcessingConfig(
    ::google::protobuf::Arena* arena, const AudioProcessingConfig& from)
    : AudioProcessingConfig(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE AudioProcessingConfig::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void AudioProcessingConfig::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, threshold_),
           0,
           offsetof(Impl_, sample_rate_) -
               offsetof(Impl_, threshold_) +
               sizeof(Impl_::sample_rate_));
}
AudioProcessingConfig::~AudioProcessingConfig() {
  // @@protoc_insertion_point(destructor:audioproc.AudioProcessingConfig)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void AudioProcessingConfig::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
AudioProcessingConfig::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(AudioProcessingConfig, _impl_._cached_size_),
              false,
          },
          &AudioProcessingConfig::MergeImpl,
          &AudioProcessingConfig::kDescriptorMethods,
          &descriptor_table_proto_2faudio_5fprocessor_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 8, 0, 0, 2> AudioProcessingConfig::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    8, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967040,  // skipmap
    offsetof(decltype(_table_), field_entries),
    8,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_AudioProcessingConfig_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::audioproc::AudioProcessingConfig>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 sample_rate = 8;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(AudioProcessingConfig, _impl_.sample_rate_), 63>(),
     {64, 63, 0, PROTOBUF_FIELD_OFFSET(AudioProcessingConfig, _impl_.sample_rate_)}},
    // float threshold = 1;
    {::_pbi::TcParser::FastF32S1,
     {13, 63, 0, PROTOBUF_FIELD_OFFSET(AudioProcessingConfig, _impl_.threshold_)}},
    // int32 margin = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(AudioProcessingConfig, _impl_.margin_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(AudioProcessingConfig, _impl_.margin_)}},
    // float high_pass = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 63, 0, PROTOBUF_FIELD_OFFSET(AudioProcessingConfig, _impl_.high_pass_)}},
    // bool use_bandpass = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(AudioProcessingConfig, _impl_.use_bandpass_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(AudioProcessingConfig, _impl_.use_bandpass_)}},
    // float band_low = 5;
    {::_pbi::TcParser::FastF32S1,
     {45, 63, 0, PROTOBUF_FIELD_OFFSET(AudioProcessingConfig, _impl_.band_low_)}},
    // float band_high = 6;
    {::_pbi::TcParser::FastF32S1,
     {53, 63, 0, PROTOBUF_FIELD_OFFSET(AudioProcessingConfig, _impl_.band_high_)}},
    // int32 fade_samples = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(AudioProcessingConfig, _impl_.fade_samples_), 63>(),
     {56, 63, 0, PROTOBUF_FIELD_OFFSET(AudioProcessingConfig, _impl_.fade_samples_)}},
  }}, {{
    65535, 65535
  }}, {{
    // float threshold = 1;
    {PROTOBUF_FIELD_OFFSET(AudioProcessingConfig, _impl_.threshold_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // int32 margin = 2;
    {PROTOBUF_FIELD_OFFSET(AudioProcessingConfig, _impl_.margin_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // float high_pass = 3;
    {PROTOBUF_FIELD_OFFSET(AudioProcessingConfig, _impl_.high_pass_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // bool use_bandpass = 4;
    {PROTOBUF_FIELD_OFFSET(AudioProcessingConfig, _impl_.use_bandpass_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // float band_low = 5;
    {PROTOBUF_FIELD_OFFSET(AudioProcessingConfig, _impl_.band_low_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float band_high = 6;
    {PROTOBUF_FIELD_OFFSET(AudioProcessingConfig, _impl_.band_high_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // int32 fade_samples = 7;
    {PROTOBUF_FIELD_OFFSET(AudioProcessingConfig, _impl_.fade_samples_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 sample_rate = 8;
    {PROTOBUF_FIELD_OFFSET(AudioProcessingConfig, _impl_.sample_rate_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void AudioProcessingConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:audioproc.AudioProcessingConfig)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.threshold_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.sample_rate_) -
      reinterpret_cast<char*>(&_impl_.threshold_)) + sizeof(_impl_.sample_rate_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* AudioProcessingConfig::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:audioproc.AudioProcessingConfig)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // float threshold = 1;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_threshold = this->_internal_threshold();
  ::uint32_t raw_threshold;
  memcpy(&raw_threshold, &tmp_threshold, sizeof(tmp_threshold));
  if (raw_threshold != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        1, this->_internal_threshold(), target);
  }

  // int32 margin = 2;
  if (this->_internal_margin() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_margin(), target);
  }

  // float high_pass = 3;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_high_pass = this->_internal_high_pass();
  ::uint32_t raw_high_pass;
  memcpy(&raw_high_pass, &tmp_high_pass, sizeof(tmp_high_pass));
  if (raw_high_pass != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        3, this->_internal_high_pass(), target);
  }

  // bool use_bandpass = 4;
  if (this->_internal_use_bandpass() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        4, this->_internal_use_bandpass(), target);
  }

  // float band_low = 5;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_band_low = this->_internal_band_low();
  ::uint32_t raw_band_low;
  memcpy(&raw_band_low, &tmp_band_low, sizeof(tmp_band_low));
  if (raw_band_low != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        5, this->_internal_band_low(), target);
  }

  // float band_high = 6;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_band_high = this->_internal_band_high();
  ::uint32_t raw_band_high;
  memcpy(&raw_band_high, &tmp_band_high, sizeof(tmp_band_high));
  if (raw_band_high != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        6, this->_internal_band_high(), target);
  }

  // int32 fade_samples = 7;
  if (this->_internal_fade_samples() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<7>(
            stream, this->_internal_fade_samples(), target);
  }

  // int32 sample_rate = 8;
  if (this->_internal_sample_rate() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<8>(
            stream, this->_internal_sample_rate(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:audioproc.AudioProcessingConfig)
  return target;
}

::size_t AudioProcessingConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:audioproc.AudioProcessingConfig)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // float threshold = 1;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_threshold = this->_internal_threshold();
  ::uint32_t raw_threshold;
  memcpy(&raw_threshold, &tmp_threshold, sizeof(tmp_threshold));
  if (raw_threshold != 0) {
    total_size += 5;
  }

  // int32 margin = 2;
  if (this->_internal_margin() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_margin());
  }

  // float high_pass = 3;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_high_pass = this->_internal_high_pass();
  ::uint32_t raw_high_pass;
  memcpy(&raw_high_pass, &tmp_high_pass, sizeof(tmp_high_pass));
  if (raw_high_pass != 0) {
    total_size += 5;
  }

  // bool use_bandpass = 4;
  if (this->_internal_use_bandpass() != 0) {
    total_size += 2;
  }

  // float band_low = 5;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_band_low = this->_internal_band_low();
  ::uint32_t raw_band_low;
  memcpy(&raw_band_low, &tmp_band_low, sizeof(tmp_band_low));
  if (raw_band_low != 0) {
    total_size += 5;
  }

  // float band_high = 6;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_band_high = this->_internal_band_high();
  ::uint32_t raw_band_high;
  memcpy(&raw_band_high, &tmp_band_high, sizeof(tmp_band_high));
  if (raw_band_high != 0) {
    total_size += 5;
  }

  // int32 fade_samples = 7;
  if (this->_internal_fade_samples() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_fade_samples());
  }

  // int32 sample_rate = 8;
  if (this->_internal_sample_rate() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_sample_rate());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void AudioProcessingConfig::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<AudioProcessingConfig*>(&to_msg);
  auto& from = static_cast<const AudioProcessingConfig&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:audioproc.AudioProcessingConfig)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_threshold = from._internal_threshold();
  ::uint32_t raw_threshold;
  memcpy(&raw_threshold, &tmp_threshold, sizeof(tmp_threshold));
  if (raw_threshold != 0) {
    _this->_impl_.threshold_ = from._impl_.threshold_;
  }
  if (from._internal_margin() != 0) {
    _this->_impl_.margin_ = from._impl_.margin_;
  }
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_high_pass = from._internal_high_pass();
  ::uint32_t raw_high_pass;
  memcpy(&raw_high_pass, &tmp_high_pass, sizeof(tmp_high_pass));
  if (raw_high_pass != 0) {
    _this->_impl_.high_pass_ = from._impl_.high_pass_;
  }
  if (from._internal_use_bandpass() != 0) {
    _this->_impl_.use_bandpass_ = from._impl_.use_bandpass_;
  }
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_band_low = from._internal_band_low();
  ::uint32_t raw_band_low;
  memcpy(&raw_band_low, &tmp_band_low, sizeof(tmp_band_low));
  if (raw_band_low != 0) {
    _this->_impl_.band_low_ = from._impl_.band_low_;
  }
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_band_high = from._internal_band_high();
  ::uint32_t raw_band_high;
  memcpy(&raw_band_high, &tmp_band_high, sizeof(tmp_band_high));
  if (raw_band_high != 0) {
    _this->_impl_.band_high_ = from._impl_.band_high_;
  }
  if (from._internal_fade_samples() != 0) {
    _this->_impl_.fade_samples_ = from._impl_.fade_samples_;
  }
  if (from._internal_sample_rate() != 0) {
    _this->_impl_.sample_rate_ = from._impl_.sample_rate_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AudioProcessingConfig::CopyFrom(const AudioProcessingConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:audioproc.AudioProcessingConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AudioProcessingConfig::InternalSwap(AudioProcessingConfig* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AudioProcessingConfig, _impl_.sample_rate_)
      + sizeof(AudioProcessingConfig::_impl_.sample_rate_)
      - PROTOBUF_FIELD_OFFSET(AudioProcessingConfig, _impl_.threshold_)>(
          reinterpret_cast<char*>(&_impl_.threshold_),
          reinterpret_cast<char*>(&other->_impl_.threshold_));
}

::google::protobuf::Metadata AudioProcessingConfig::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ProcessAudioRequest::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ProcessAudioRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ProcessAudioRequest, _impl_._has_bits_);
};

ProcessAudioRequest::ProcessAudioRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:audioproc.ProcessAudioRequest)
}
inline PROTOBUF_NDEBUG_INLINE ProcessAudioRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::audioproc::ProcessAudioRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        wav_data_(arena, from.wav_data_),
        file_name_(arena, from.file_name_) {}

ProcessAudioRequest::ProcessAudioRequest(
    ::google::protobuf::Arena* arena,
    const ProcessAudioRequest& from)
    : ::google::protobuf::Message(arena) {
  ProcessAudioRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.config_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::audioproc::AudioProcessingConfig>(
                              arena, *from._impl_.config_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:audioproc.ProcessAudioRequest)
}
inline PROTOBUF_NDEBUG_INLINE ProcessAudioRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        wav_data_(arena),
        file_name_(arena) {}

inline void ProcessAudioRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.config_ = {};
}
ProcessAudioRequest::~ProcessAudioRequest() {
  // @@protoc_insertion_point(destructor:audioproc.ProcessAudioRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ProcessAudioRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.wav_data_.Destroy();
  _impl_.file_name_.Destroy();
  delete _impl_.config_;
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
ProcessAudioRequest::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(ProcessAudioRequest, _impl_._cached_size_),
              false,
          },
          &ProcessAudioRequest::MergeImpl,
          &ProcessAudioRequest::kDescriptorMethods,
          &descriptor_table_proto_2faudio_5fprocessor_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 47, 2> ProcessAudioRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ProcessAudioRequest, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_ProcessAudioRequest_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::audioproc::ProcessAudioRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // bytes wav_data = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ProcessAudioRequest, _impl_.wav_data_)}},
    // string file_name = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(ProcessAudioRequest, _impl_.file_name_)}},
    // .audioproc.AudioProcessingConfig config = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(ProcessAudioRequest, _impl_.config_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes wav_data = 1;
    {PROTOBUF_FIELD_OFFSET(ProcessAudioRequest, _impl_.wav_data_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // string file_name = 2;
    {PROTOBUF_FIELD_OFFSET(ProcessAudioRequest, _impl_.file_name_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .audioproc.AudioProcessingConfig config = 3;
    {PROTOBUF_FIELD_OFFSET(ProcessAudioRequest, _impl_.config_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::audioproc::AudioProcessingConfig>()},
  }}, {{
    "\35\0\11\0\0\0\0\0"
    "audioproc.ProcessAudioRequest"
    "file_name"
  }},
};

PROTOBUF_NOINLINE void ProcessAudioRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:audioproc.ProcessAudioRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.wav_data_.ClearToEmpty();
  _impl_.file_name_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.config_ != nullptr);
    _impl_.config_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* ProcessAudioRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:audioproc.ProcessAudioRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bytes wav_data = 1;
  if (!this->_internal_wav_data().empty()) {
    const std::string& _s = this->_internal_wav_data();
    target = stream->WriteBytesMaybeAliased(1, _s, target);
  }

  // string file_name = 2;
  if (!this->_internal_file_name().empty()) {
    const std::string& _s = this->_internal_file_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "audioproc.ProcessAudioRequest.file_name");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // .audioproc.AudioProcessingConfig config = 3;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *_impl_.config_, _impl_.config_->GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:audioproc.ProcessAudioRequest)
  return target;
}

::size_t ProcessAudioRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:audioproc.ProcessAudioRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // bytes wav_data = 1;
  if (!this->_internal_wav_data().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_wav_data());
  }

  // string file_name = 2;
  if (!this->_internal_file_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_file_name());
  }

  // .audioproc.AudioProcessingConfig config = 3;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size +=
        1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.config_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void ProcessAudioRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ProcessAudioRequest*>(&to_msg);
  auto& from = static_cast<const ProcessAudioRequest&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:audioproc.ProcessAudioRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_wav_data().empty()) {
    _this->_internal_set_wav_data(from._internal_wav_data());
  }
  if (!from._internal_file_name().empty()) {
    _this->_internal_set_file_name(from._internal_file_name());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.config_ != nullptr);
    if (_this->_impl_.config_ == nullptr) {
      _this->_impl_.config_ =
          ::google::protobuf::Message::CopyConstruct<::audioproc::AudioProcessingConfig>(arena, *from._impl_.config_);
    } else {
      _this->_impl_.config_->MergeFrom(*from._impl_.config_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ProcessAudioRequest::CopyFrom(const ProcessAudioRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:audioproc.ProcessAudioRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ProcessAudioRequest::InternalSwap(ProcessAudioRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.wav_data_, &other->_impl_.wav_data_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.file_name_, &other->_impl_.file_name_, arena);
  swap(_impl_.config_, other->_impl_.config_);
}

::google::protobuf::Metadata ProcessAudioRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ProcessAudioResponse::_Internal {
 public:
};

ProcessAudioResponse::ProcessAudioResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:audioproc.ProcessAudioResponse)
}
inline PROTOBUF_NDEBUG_INLINE ProcessAudioResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::audioproc::ProcessAudioResponse& from_msg)
      : wav_data_(arena, from.wav_data_),
        _cached_size_{0} {}

ProcessAudioResponse::ProcessAudioResponse(
    ::google::protobuf::Arena* arena,
    const ProcessAudioResponse& from)
    : ::google::protobuf::Message(arena) {
  ProcessAudioResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:audioproc.ProcessAudioResponse)
}
inline PROTOBUF_NDEBUG_INLINE ProcessAudioResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : wav_data_(arena),
        _cached_size_{0} {}

inline void ProcessAudioResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ProcessAudioResponse::~ProcessAudioResponse() {
  // @@protoc_insertion_point(destructor:audioproc.ProcessAudioResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ProcessAudioResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.wav_data_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
ProcessAudioResponse::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(ProcessAudioResponse, _impl_._cached_size_),
              false,
          },
          &ProcessAudioResponse::MergeImpl,
          &ProcessAudioResponse::kDescriptorMethods,
          &descriptor_table_proto_2faudio_5fprocessor_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> ProcessAudioResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ProcessAudioResponse_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::audioproc::ProcessAudioResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes wav_data = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ProcessAudioResponse, _impl_.wav_data_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes wav_data = 1;
    {PROTOBUF_FIELD_OFFSET(ProcessAudioResponse, _impl_.wav_data_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void ProcessAudioResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:audioproc.ProcessAudioResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.wav_data_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* ProcessAudioResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:audioproc.ProcessAudioResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bytes wav_data = 1;
  if (!this->_internal_wav_data().empty()) {
    const std::string& _s = this->_internal_wav_data();
    target = stream->WriteBytesMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:audioproc.ProcessAudioResponse)
  return target;
}

::size_t ProcessAudioResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:audioproc.ProcessAudioResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes wav_data = 1;
  if (!this->_internal_wav_data().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_wav_data());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void ProcessAudioResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ProcessAudioResponse*>(&to_msg);
  auto& from = static_cast<const ProcessAudioResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:audioproc.ProcessAudioResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_wav_data().empty()) {
    _this->_internal_set_wav_data(from._internal_wav_data());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ProcessAudioResponse::CopyFrom(const ProcessAudioResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:audioproc.ProcessAudioResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ProcessAudioResponse::InternalSwap(ProcessAudioResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.wav_data_, &other->_impl_.wav_data_, arena);
}

::google::protobuf::Metadata ProcessAudioResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace audioproc
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_proto_2faudio_5fprocessor_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
