// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: audio.proto

package audioproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AudioAnalyzer_ProcessAudio_FullMethodName = "/audio.AudioAnalyzer/ProcessAudio"
)

// AudioAnalyzerClient is the client API for AudioAnalyzer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AudioAnalyzerClient interface {
	ProcessAudio(ctx context.Context, in *AudioRequest, opts ...grpc.CallOption) (*AudioResponse, error)
}

type audioAnalyzerClient struct {
	cc grpc.ClientConnInterface
}

func NewAudioAnalyzerClient(cc grpc.ClientConnInterface) AudioAnalyzerClient {
	return &audioAnalyzerClient{cc}
}

func (c *audioAnalyzerClient) ProcessAudio(ctx context.Context, in *AudioRequest, opts ...grpc.CallOption) (*AudioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AudioResponse)
	err := c.cc.Invoke(ctx, AudioAnalyzer_ProcessAudio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AudioAnalyzerServer is the server API for AudioAnalyzer service.
// All implementations must embed UnimplementedAudioAnalyzerServer
// for forward compatibility.
type AudioAnalyzerServer interface {
	ProcessAudio(context.Context, *AudioRequest) (*AudioResponse, error)
	mustEmbedUnimplementedAudioAnalyzerServer()
}

// UnimplementedAudioAnalyzerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAudioAnalyzerServer struct{}

func (UnimplementedAudioAnalyzerServer) ProcessAudio(context.Context, *AudioRequest) (*AudioResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessAudio not implemented")
}
func (UnimplementedAudioAnalyzerServer) mustEmbedUnimplementedAudioAnalyzerServer() {}
func (UnimplementedAudioAnalyzerServer) testEmbeddedByValue()                       {}

// UnsafeAudioAnalyzerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AudioAnalyzerServer will
// result in compilation errors.
type UnsafeAudioAnalyzerServer interface {
	mustEmbedUnimplementedAudioAnalyzerServer()
}

func RegisterAudioAnalyzerServer(s grpc.ServiceRegistrar, srv AudioAnalyzerServer) {
	// If the following call pancis, it indicates UnimplementedAudioAnalyzerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AudioAnalyzer_ServiceDesc, srv)
}

func _AudioAnalyzer_ProcessAudio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AudioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioAnalyzerServer).ProcessAudio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AudioAnalyzer_ProcessAudio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioAnalyzerServer).ProcessAudio(ctx, req.(*AudioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AudioAnalyzer_ServiceDesc is the grpc.ServiceDesc for AudioAnalyzer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AudioAnalyzer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "audio.AudioAnalyzer",
	HandlerType: (*AudioAnalyzerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessAudio",
			Handler:    _AudioAnalyzer_ProcessAudio_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "audio.proto",
}
