// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: riff.proto

package riffproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RiffGenerator_GenerateRiff_FullMethodName = "/riff.RiffGenerator/GenerateRiff"
)

// RiffGeneratorClient is the client API for RiffGenerator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RiffGeneratorClient interface {
	GenerateRiff(ctx context.Context, in *RiffRequest, opts ...grpc.CallOption) (*RiffResponse, error)
}

type riffGeneratorClient struct {
	cc grpc.ClientConnInterface
}

func NewRiffGeneratorClient(cc grpc.ClientConnInterface) RiffGeneratorClient {
	return &riffGeneratorClient{cc}
}

func (c *riffGeneratorClient) GenerateRiff(ctx context.Context, in *RiffRequest, opts ...grpc.CallOption) (*RiffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RiffResponse)
	err := c.cc.Invoke(ctx, RiffGenerator_GenerateRiff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RiffGeneratorServer is the server API for RiffGenerator service.
// All implementations must embed UnimplementedRiffGeneratorServer
// for forward compatibility.
type RiffGeneratorServer interface {
	GenerateRiff(context.Context, *RiffRequest) (*RiffResponse, error)
	mustEmbedUnimplementedRiffGeneratorServer()
}

// UnimplementedRiffGeneratorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRiffGeneratorServer struct{}

func (UnimplementedRiffGeneratorServer) GenerateRiff(context.Context, *RiffRequest) (*RiffResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateRiff not implemented")
}
func (UnimplementedRiffGeneratorServer) mustEmbedUnimplementedRiffGeneratorServer() {}
func (UnimplementedRiffGeneratorServer) testEmbeddedByValue()                       {}

// UnsafeRiffGeneratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RiffGeneratorServer will
// result in compilation errors.
type UnsafeRiffGeneratorServer interface {
	mustEmbedUnimplementedRiffGeneratorServer()
}

func RegisterRiffGeneratorServer(s grpc.ServiceRegistrar, srv RiffGeneratorServer) {
	// If the following call pancis, it indicates UnimplementedRiffGeneratorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RiffGenerator_ServiceDesc, srv)
}

func _RiffGenerator_GenerateRiff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RiffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiffGeneratorServer).GenerateRiff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiffGenerator_GenerateRiff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiffGeneratorServer).GenerateRiff(ctx, req.(*RiffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RiffGenerator_ServiceDesc is the grpc.ServiceDesc for RiffGenerator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RiffGenerator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "riff.RiffGenerator",
	HandlerType: (*RiffGeneratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateRiff",
			Handler:    _RiffGenerator_GenerateRiff_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "riff.proto",
}
