// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: onsets_and_frames.proto

package onsets_frames

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OnsetsAndFrames_Analyze_FullMethodName = "/onsetsframes.OnsetsAndFrames/Analyze"
)

// OnsetsAndFramesClient is the client API for OnsetsAndFrames service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OnsetsAndFramesClient interface {
	Analyze(ctx context.Context, in *OAFRequest, opts ...grpc.CallOption) (*OAFResponse, error)
}

type onsetsAndFramesClient struct {
	cc grpc.ClientConnInterface
}

func NewOnsetsAndFramesClient(cc grpc.ClientConnInterface) OnsetsAndFramesClient {
	return &onsetsAndFramesClient{cc}
}

func (c *onsetsAndFramesClient) Analyze(ctx context.Context, in *OAFRequest, opts ...grpc.CallOption) (*OAFResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OAFResponse)
	err := c.cc.Invoke(ctx, OnsetsAndFrames_Analyze_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OnsetsAndFramesServer is the server API for OnsetsAndFrames service.
// All implementations must embed UnimplementedOnsetsAndFramesServer
// for forward compatibility.
type OnsetsAndFramesServer interface {
	Analyze(context.Context, *OAFRequest) (*OAFResponse, error)
	mustEmbedUnimplementedOnsetsAndFramesServer()
}

// UnimplementedOnsetsAndFramesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOnsetsAndFramesServer struct{}

func (UnimplementedOnsetsAndFramesServer) Analyze(context.Context, *OAFRequest) (*OAFResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Analyze not implemented")
}
func (UnimplementedOnsetsAndFramesServer) mustEmbedUnimplementedOnsetsAndFramesServer() {}
func (UnimplementedOnsetsAndFramesServer) testEmbeddedByValue()                         {}

// UnsafeOnsetsAndFramesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OnsetsAndFramesServer will
// result in compilation errors.
type UnsafeOnsetsAndFramesServer interface {
	mustEmbedUnimplementedOnsetsAndFramesServer()
}

func RegisterOnsetsAndFramesServer(s grpc.ServiceRegistrar, srv OnsetsAndFramesServer) {
	// If the following call pancis, it indicates UnimplementedOnsetsAndFramesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OnsetsAndFrames_ServiceDesc, srv)
}

func _OnsetsAndFrames_Analyze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OAFRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnsetsAndFramesServer).Analyze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnsetsAndFrames_Analyze_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnsetsAndFramesServer).Analyze(ctx, req.(*OAFRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OnsetsAndFrames_ServiceDesc is the grpc.ServiceDesc for OnsetsAndFrames service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OnsetsAndFrames_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "onsetsframes.OnsetsAndFrames",
	HandlerType: (*OnsetsAndFramesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Analyze",
			Handler:    _OnsetsAndFrames_Analyze_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "onsets_and_frames.proto",
}
