# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: riff.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'riff.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nriff.proto\x12\x04riff\"7\n\x0bRiffRequest\x12\x0c\n\x04tone\x18\x01 \x01(\t\x12\x1a\n\x05style\x18\x02 \x01(\x0e\x32\x0b.riff.Style\"\x1c\n\x0cRiffResponse\x12\x0c\n\x04riff\x18\x01 \x01(\t*L\n\x05Style\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x08\n\x04ROCK\x10\x01\x12\t\n\x05\x42LUES\x10\x02\x12\t\n\x05METAL\x10\x03\x12\x08\n\x04JAZZ\x10\x04\x12\x08\n\x04\x46UNK\x10\x05\x32\x46\n\rRiffGenerator\x12\x35\n\x0cGenerateRiff\x12\x11.riff.RiffRequest\x1a\x12.riff.RiffResponseB\x14Z\x12internal/riffprotob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'riff_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\022internal/riffproto'
  _globals['_STYLE']._serialized_start=107
  _globals['_STYLE']._serialized_end=183
  _globals['_RIFFREQUEST']._serialized_start=20
  _globals['_RIFFREQUEST']._serialized_end=75
  _globals['_RIFFRESPONSE']._serialized_start=77
  _globals['_RIFFRESPONSE']._serialized_end=105
  _globals['_RIFFGENERATOR']._serialized_start=185
  _globals['_RIFFGENERATOR']._serialized_end=255
# @@protoc_insertion_point(module_scope)
