// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: fx_processor.proto

package fxprocessorproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FXProcessor_ProcessAudio_FullMethodName = "/fxp.FXProcessor/ProcessAudio"
)

// FXProcessorClient is the client API for FXProcessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FXProcessorClient interface {
	ProcessAudio(ctx context.Context, in *AudioRequest, opts ...grpc.CallOption) (*AudioRequest, error)
}

type fXProcessorClient struct {
	cc grpc.ClientConnInterface
}

func NewFXProcessorClient(cc grpc.ClientConnInterface) FXProcessorClient {
	return &fXProcessorClient{cc}
}

func (c *fXProcessorClient) ProcessAudio(ctx context.Context, in *AudioRequest, opts ...grpc.CallOption) (*AudioRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AudioRequest)
	err := c.cc.Invoke(ctx, FXProcessor_ProcessAudio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FXProcessorServer is the server API for FXProcessor service.
// All implementations must embed UnimplementedFXProcessorServer
// for forward compatibility.
type FXProcessorServer interface {
	ProcessAudio(context.Context, *AudioRequest) (*AudioRequest, error)
	mustEmbedUnimplementedFXProcessorServer()
}

// UnimplementedFXProcessorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFXProcessorServer struct{}

func (UnimplementedFXProcessorServer) ProcessAudio(context.Context, *AudioRequest) (*AudioRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessAudio not implemented")
}
func (UnimplementedFXProcessorServer) mustEmbedUnimplementedFXProcessorServer() {}
func (UnimplementedFXProcessorServer) testEmbeddedByValue()                     {}

// UnsafeFXProcessorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FXProcessorServer will
// result in compilation errors.
type UnsafeFXProcessorServer interface {
	mustEmbedUnimplementedFXProcessorServer()
}

func RegisterFXProcessorServer(s grpc.ServiceRegistrar, srv FXProcessorServer) {
	// If the following call pancis, it indicates UnimplementedFXProcessorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FXProcessor_ServiceDesc, srv)
}

func _FXProcessor_ProcessAudio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AudioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FXProcessorServer).ProcessAudio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FXProcessor_ProcessAudio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FXProcessorServer).ProcessAudio(ctx, req.(*AudioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FXProcessor_ServiceDesc is the grpc.ServiceDesc for FXProcessor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FXProcessor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fxp.FXProcessor",
	HandlerType: (*FXProcessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessAudio",
			Handler:    _FXProcessor_ProcessAudio_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fx_processor.proto",
}
