name: Guitar Workshop CI (Go)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  go:
    name: Build & Test Go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'
      - name: Build
        run: go build ./...
      - name: Test
        run: go test ./...

  # python:
  #   name: Check Python
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.10'
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt
  #     - name: Check import
  #       run: python -c "import basic_pitch"

  # cpp:
  #   name: Build C++ (audio-preprocessor)
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install dependencies
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install -y cmake g++ libsndfile1-dev
  #     - name: Set up Conan
  #       uses: conan-io/conan-center-index@v1
  #     - name: Configure CMake
  #       run: |
  #         mkdir build && cd build
  #         conan install .. --build=missing
  #         cmake .. -DCMAKE_BUILD_TYPE=Release
  #     - name: Build
  #       run: cd build && cmake --build . --config Release
